apiVersion: v1
kind: Secret
metadata:
  name: movie-db-adminpass
type: Opaque
data:
  password: bW92aWVfZGJfcGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: cast-db-adminpass
type: Opaque
data:
  password: Y2FzdF9kYl9wYXNzd29yZA==
