apiVersion: v1
kind: Service
metadata:
  name: movie-app
spec:
  type: ClusterIP
  ports:
  - name: api
    port: 8000
    targetPort: api
    protocol: TCP
  selector:
    app: movie-app
---
apiVersion: v1
kind: Service
metadata:
  name: movie-db
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: postgres
    protocol: TCP
  selector:
    app: movie-db
---
apiVersion: v1
kind: Service
metadata:
  name: cast-app
spec:
  type: ClusterIP
  ports:
  - name: api
    port: 8000
    targetPort: api
    protocol: TCP
  selector:
    app: cast-app
---
apiVersion: v1
kind: Service
metadata:
  name: cast-db
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: postgres
    protocol: TCP
  selector:
    app: cast-db
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - nodePort: {{ .Values.service.nodePort }}
      port: 8080
      targetPort: http
      protocol: TCP
